const instructionText = {
    "Texture/Colour": "This visualization shows the spread of hydrocarbon contamination at a site and certainty of the model.\n The concentration of the pollutants is shown as different colours and the certainty of the model is shown as different textures (e.g., dotting, cross-hatching).\n The sensors are marked by a blue triangle.",
    "HSV": "This visualization shows the spread of hydrocarbon contamination in an area, as well as the model's certainty of hydrocarbons at that location. Certainty is based on the distance from the sensors.\nThe sensors are marked by a blue triangle.\nThe higher colour saturation shows the higher certainty of the model.\nThe value of the colour shows how high the concentration of hydrocarbons is at that location.",
    "Static/Animated": "This visualization shows various results of a modelling algorithm that predicts the extent of hydrocarbon contamination at a location.\nDifferent outcomes from the model are shown in this type of visualization. Each boundary line represents a single outcome of the model.\nThe sensors are marked by a blue triangle.",
    "VSUP": "This visualization uses a value-suppressed uncertainty palette to show both hydrocarbon contamination and certainty of the model.\nA value-suppressed uncertainty palette maps a value (i.e., concentration) on the x-axis, with values increasing as the palette moves to the right (as shown on the legend).\nA second value (i.e., certainty) maps to the palette on the y-axis, with the most certain values located at the top of the palette.\nFor example, the value at point \"A\" scores low in concentration, but high in certainty. The value at point \"B\" has a higher concentration than point \"A\", but also more uncertainty.\nThe sensors are marked by a blue triangle.",
    "Multiples": "This visualization shows various results of a modelling algorithm that predicts the extent of hydrocarbon contamination at a location.\nDifferent outcomes from the model are shown in this type of visualization. Each image in the grid represents a single outcome of the model.\nThe sensors are marked by a blue triangle.",
    "Separate": "This visualization shows the spread of hydrocarbon contamination in an area, as well as the model's certainty of hydrocarbons at that location.\nThe certainty is represented in the top image and the concentration of the pollutants is represented in the bottom image.\nThe sensors are marked by a blue triangle.",
    "Mouseover": "This visualization shows the extent of hydrocarbon contamination at a location and the certainty of the underlying statistical model.\nThe concentration of the pollutants is indicated by the coloured areas on the image. The certainty of the model at any location is provided in a mouseover tooltip.\nThe tooltip can be accessed by hovering the mouse over any area on the map.\nThe sensors are marked by a blue triangle.",
    "Animated": "This visualization shows various results of a modelling algorithm that predicts the extent of hydrocarbon contamination at a location.\nDifferent outcomes from the model are shown in this type of visualization. Each boundary line represents a single outcome of the model.\nThe sensors are marked by a blue triangle.",
}